---
- name: Collect all BIG-IP information
  f5networks.f5_modules.bigip_device_info:
    provider: "{{ provider }}"
    gather_subset:
      - license
  register: license_info
  delegate_to: localhost

- name: "Display current license information"
  debug:
    msg: "Current license key is {{ license_info.license.registration_key }}"
    msg: "Saved license key is {{ license_key }}"

- name: Refresh license
  f5networks.f5_modules.bigip_device_license:
    provider: "{{provider}}"
    license_key: "{{ license_key }}"
    accept_eula: true
    force: true
    state: latest
  delegate_to: localhost
