---
# Provider to connect to BIG-IP
provider:
  server: "{{ ansible_host }}"
  user: "{{ansible_user}}"
  password: "{{ansible_password}}"
  no_f5_teem: false
  server_port: 443
  validate_certs: false
