---
#Create UCS File and store it on the Local Ansible Node that executed.
- name: Create and Download a UCS
  f5networks.f5_modules.bigip_ucs_fetch:
    src: "{{ ucsfilename }}"
    dest: "{{ backup_dir }}/{{ ucsfilename }}"
    provider: "{{ provider }}"
    async_timeout: 300
  retries: 5
  delay: 60
  register: result
  until: result.changed == true
  delegate_to: localhost
