---
- name: BIG-IP create UCS and save locally off-box
  hosts: lb
  connection: local
  gather_facts: false
  vars:
    filename: "{{ lookup('pipe', 'date +%FT%H%MZ') }}-{{ inventory_hostname }}-backup.ucs"

  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_ssh_pass}}"
          server_port: 443
          validate_certs: false

    - name: CREATE UCS
      f5networks.f5_modules.bigip_ucs_fetch:
        provider: "{{provider}}"
        dest: /tmp/{{filename}}
        backup: true
      delegate_to: localhost


